version: "3"

services:
  nodeosd:
    build:
      context: .
    image: achain/actx
    command: /opt/achain/bin/nodeosd.sh --data-dir /opt/achain/bin/data-dir -e --http-alias=nodeosd:8888 --http-alias=127.0.0.1:8888 --http-alias=localhost:8888 --genesis-json /genesis.json
    hostname: nodeosd
    ports:
      - 8888:8888
      - 9876:9876
    expose:
      - "8888"
    volumes:
      - nodeos-data-volume:/opt/achain/bin/data-dir
    cap_add:
      - IPC_LOCK
    stop_grace_period: 10m

  keosd:
    image: achain/actx
    command: /opt/achain/bin/keosd --wallet-dir /opt/achain/bin/data-dir --http-server-address=127.0.0.1:8900 --http-alias=keosd:8900 --http-alias=localhost:8900
    hostname: keosd
    links:
      - nodeosd
    volumes:
      - keosd-data-volume:/opt/achain/bin/data-dir
    stop_grace_period: 10m

volumes:
  nodeos-data-volume:
    external: true
  keosd-data-volume:
    external: true
